#!/bin/bash
wget -P /home/hadoop/data/ https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-01.csv;
hdfs dfs -mkdir /user/hadoop/yellow01;
hdfs dfs -chmod 777 /user/hadoop/yellow01;
hdfs dfs -put /home/hadoop/data/yellow_tripdata_2015-01.csv /user/hadoop/yellow12/yellow01.csv;
hdfs dfs -chmod 777 /user/hadoop/yellow01/yellow01.csv;
rm /home/hadoop/data/yellow_tripdata_2015-01.csv;
wget -P /home/hadoop/data/ https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-02.csv;
hdfs dfs -mkdir /user/hadoop/yellow02;
hdfs dfs -chmod 777 /user/hadoop/yellow02;
hdfs dfs -put /home/hadoop/data/yellow_tripdata_2015-02.csv /user/hadoop/yellow02/yellow02.csv;
hdfs dfs -chmod 777 /user/hadoop/yellow02/yellow02.csv;
rm /home/hadoop/data/yellow_tripdata_2015-02.csv;
wget -P /home/hadoop/data/ https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-03.csv;
hdfs dfs -mkdir /user/hadoop/yellow03;
hdfs dfs -chmod 777 /user/hadoop/yellow03;
hdfs dfs -put /home/hadoop/data/yellow_tripdata_2015-03.csv /user/hadoop/yellow03/yellow03.csv;
hdfs dfs -chmod 777 /user/hadoop/yellow03/yellow03.csv;
rm /home/hadoop/data/yellow_tripdata_2015-03.csv;
wget -P /home/hadoop/data/ https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-04.csv;
hdfs dfs -mkdir /user/hadoop/yellow04;
hdfs dfs -chmod 777 /user/hadoop/yellow04;
hdfs dfs -put /home/hadoop/data/yellow_tripdata_2015-04.csv /user/hadoop/yellow04/yellow04.csv;
hdfs dfs -chmod 777 /user/hadoop/yellow04/yellow04.csv;
rm /home/hadoop/data/yellow_tripdata_2015-04.csv;
wget -P /home/hadoop/data/ https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-05.csv;
hdfs dfs -mkdir /user/hadoop/yellow05;
hdfs dfs -chmod 777 /user/hadoop/yellow05;
hdfs dfs -put /home/hadoop/data/yellow_tripdata_2015-05.csv /user/hadoop/yellow05/yellow05.csv;
hdfs dfs -chmod 777 /user/hadoop/yellow05/yellow05.csv;
rm /home/hadoop/data/yellow_tripdata_2015-05.csv;
wget -P /home/hadoop/data/ https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-06.csv;
hdfs dfs -mkdir /user/hadoop/yellow06;
hdfs dfs -chmod 777 /user/hadoop/yellow06;
hdfs dfs -put /home/hadoop/data/yellow_tripdata_2015-06.csv /user/hadoop/yellow06/yellow06.csv;
hdfs dfs -chmod 777 /user/hadoop/yellow06/yellow06.csv;
rm /home/hadoop/data/yellow_tripdata_2015-06.csv;
wget -P /home/hadoop/data/ https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-07.csv;
hdfs dfs -mkdir /user/hadoop/yellow07;
hdfs dfs -chmod 777 /user/hadoop/yellow07;
hdfs dfs -put /home/hadoop/data/yellow_tripdata_2015-07.csv /user/hadoop/yellow07/yellow07.csv;
hdfs dfs -chmod 777 /user/hadoop/yellow07/yellow07.csv;
rm /home/hadoop/data/yellow_tripdata_2015-07.csv;
wget -P /home/hadoop/data/ https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-08.csv;
hdfs dfs -mkdir /user/hadoop/yellow08;
hdfs dfs -chmod 777 /user/hadoop/yellow08;
hdfs dfs -put /home/hadoop/data/yellow_tripdata_2015-08.csv /user/hadoop/yellow08/yellow08.csv;
hdfs dfs -chmod 777 /user/hadoop/yellow08/yellow08.csv;
rm /home/hadoop/data/yellow_tripdata_2015-08.csv;
wget -P /home/hadoop/data/ https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-09.csv;
hdfs dfs -mkdir /user/hadoop/yellow09;
hdfs dfs -chmod 777 /user/hadoop/yellow09;
hdfs dfs -put /home/hadoop/data/yellow_tripdata_2015-09.csv /user/hadoop/yellow09/yellow09.csv;
hdfs dfs -chmod 777 /user/hadoop/yellow09/yellow09.csv;
rm /home/hadoop/data/yellow_tripdata_2015-09.csv;
wget -P /home/hadoop/data/ https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-10.csv;
hdfs dfs -mkdir /user/hadoop/yellow10;
hdfs dfs -chmod 777 /user/hadoop/yellow10;
hdfs dfs -put /home/hadoop/data/yellow_tripdata_2015-10.csv /user/hadoop/yellow10/yellow10.csv;
hdfs dfs -chmod 777 /user/hadoop/yellow10/yellow10.csv;
rm /home/hadoop/data/yellow_tripdata_2015-10.csv;
wget -P /home/hadoop/data/ https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-11.csv;
hdfs dfs -mkdir /user/hadoop/yellow11;
hdfs dfs -chmod 777 /user/hadoop/yellow11;
hdfs dfs -put /home/hadoop/data/yellow_tripdata_2015-11.csv /user/hadoop/yellow11/yellow11.csv;
hdfs dfs -chmod 777 /user/hadoop/yellow11/yellow11.csv;
rm /home/hadoop/data/yellow_tripdata_2015-11.csv;
wget -P /home/hadoop/data/ https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2015-12.csv;
hdfs dfs -mkdir /user/hadoop/yellow12;
hdfs dfs -chmod 777 /user/hadoop/yellow12;
hdfs dfs -put /home/hadoop/data/yellow_tripdata_2015-12.csv /user/hadoop/yellow12/yellow12.csv;
hdfs dfs -chmod 777 /user/hadoop/yellow12/yellow12.csv;
rm /home/hadoop/data/yellow_tripdata_2015-12.csv;
